name: CLI Package Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate-package:
    name: 📦 Validate CLI Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create package
        run: npm pack

      - name: Test package installation
        run: |
          npm install -g ./vdk-cli-*.tgz
          vdk --version
